import { prisma } from '../utils/prismaConnection.js';

const overviews = [
  { slug: 'pahalgam', html: "<p><strong>Are you searching for a trip to visit the famous Betaab Valley and experience exploring Aru Valley's scenic landscapes in Pahalgam?</strong></p>\n<p><strong>Arivo Holidays</strong> has crafted the ultimate itinerary for you to comfortably explore Betaab Valley and enjoy exploring Aru Valley's scenic landscapes. This journey has been planned uniquely and specially for you to ensure a stress-free vacation.</p>\n<p><strong>Scroll down to check out our hand-picked tour packages below and click to book your dream trip! 👇</strong></p>" },
  { slug: 'ranthambore', html: "<p><strong>Are you planning an adventure to visit the National Park and experience a thrilling Jungle Safari to spot Bengal Tigers in Ranthambore?</strong></p>\n<p>Your search ends here! <strong>Arivo Holidays</strong> brings you the perfect itinerary where you can freely explore the National Park and truly enjoy a thrilling Jungle Safari to spot Bengal Tigers. This travel plan is designed exclusively for you.</p>\n<p><strong>Check out our premium tour packages below and choose your favorite today! 👇</strong></p>" },
  { slug: 'bharatpur', html: "<p><strong>Are you looking forward to visiting Keoladeo National Park and experiencing peaceful Bird Watching in Bharatpur?</strong></p>\n<p>With <strong>Arivo Holidays</strong>, you get a specially designed itinerary that lets you explore Keoladeo National Park and enjoy peaceful Bird Watching without any hassle. This trip is uniquely curated just for you.</p>\n<p><strong>Scroll below to see our exclusive tour packages and book your dream getaway! 👇</strong></p>" },
  { slug: 'orchha', html: "<p><strong>Have you been wanting to visit Jahangir Mahal and experience exploring the ancient Forts in Orchha?</strong></p>\n<p><strong>Arivo Holidays</strong> has put together the best possible itinerary so you can deeply explore Jahangir Mahal and enjoy exploring the ancient Forts. We have planned this trip in a very special and unique way for you.</p>\n<p><strong>Browse our top-rated tour packages below and start planning your journey! 👇</strong></p>" },
  { slug: 'sarnath', html: "<p><strong>Are you eager to visit the Buddhist Stupas and experience seeing the historic Ashoka Pillar in Sarnath?</strong></p>\n<p>Trust <strong>Arivo Holidays</strong> to provide an incredible itinerary where you can discover the Buddhist Stupas and enjoy seeing the historic Ashoka Pillar. This package is uniquely planned for your complete peace of mind.</p>\n<p><strong>Scroll down to explore our hand-crafted tour list and book your perfect holiday! 👇</strong></p>" },
  { slug: 'khajuraho', html: "<p><strong>Are you ready to visit the UNESCO Heritage Temples and experience admiring ancient Sculptures in Khajuraho?</strong></p>\n<p><strong>Arivo Holidays</strong> has developed a brilliant itinerary for you, allowing you to seamlessly explore the UNESCO Heritage Temples and enjoy admiring ancient Sculptures. This is a very uniquely and specially planned trip just for you.</p>\n<p><strong>Take a look at our fantastic tour packages below and book your ideal trip! 👇</strong></p>" },
  { slug: 'doodhpathri', html: "<p><strong>Are you dreaming of visiting the Pine Forests and experiencing relaxing by the River Streams in Doodhpathri?</strong></p>\n<p>Look no further! <strong>Arivo Holidays</strong> has created a magical itinerary where you can explore the Pine Forests and enjoy relaxing by the River Streams. This is uniquely structured for your maximum comfort.</p>\n<p><strong>Scroll below to check our hand-picked tour list and secure your bookings today! 👇</strong></p>" },
  { slug: 'yusmarg', html: "<p><strong>Are you hoping to visit the Meadow of Jesus and experience walking through Pine Valleys in Yusmarg?</strong></p>\n<p><strong>Arivo Holidays</strong> offers the most authentic itinerary for you to explore the Meadow of Jesus and enjoy walking through Pine Valleys. Every detail is planned specially and uniquely for your enjoyment.</p>\n<p><strong>Find the best tour packages waiting for you below and click to book! 👇</strong></p>" },
  { slug: 'bikaner', html: "<p><strong>Are you looking to visit Junagarh Fort and experience an exciting Camel Safari in the desert in Bikaner?</strong></p>\n<p>Let <strong>Arivo Holidays</strong> guide you with a perfect itinerary where you can easily explore Junagarh Fort and enjoy an exciting Camel Safari in the desert. We have designed this trip uniquely for you.</p>\n<p><strong>Scroll down and click on our premium tour packages to book your next adventure! 👇</strong></p>" },
  { slug: 'doda', html: "<p><strong>Are you searching for a getaway to visit untouched natural beauty and experience serene landscapes in Doda?</strong></p>\n<p><strong>Arivo Holidays</strong> has crafted an outstanding itinerary where you can safely explore untouched natural beauty and enjoy serene landscapes. This travel plan is uniquely organized just for you.</p>\n<p><strong>Explore our best hand-picked tour list below and book your dream trip! 👇</strong></p>" },
  { slug: 'amritsar', html: "<p><strong>Are you planning to visit the Golden Temple and experience the patriotic Wagah Border ceremony in Amritsar?</strong></p>\n<p>With <strong>Arivo Holidays</strong>, you get the absolute best itinerary to explore the Golden Temple and enjoy the patriotic Wagah Border ceremony. This entire journey is specially and uniquely planned for you.</p>\n<p><strong>Scroll down to check our premium tour packages and book your ideal trip today! 👇</strong></p>" },
  { slug: 'katra', html: "<p><strong>Are you looking to visit the holy mountains and experience starting your Pilgrimage to Mata Vaishno Devi in Katra?</strong></p>\n<p><strong>Arivo Holidays</strong> has created a highly spiritual itinerary for you where you can explore the holy mountains and smoothly enjoy starting your Pilgrimage to Mata Vaishno Devi. This plan is uniquely crafted for your devotion.</p>\n<p><strong>Check out our top-tier tour packages below and click to book your journey! 👇</strong></p>" },
  { slug: 'pushkar', html: "<p><strong>Are you excited to visit the Brahma Temple and experience an exciting Camel Safari near the Pushkar Lake in Pushkar?</strong></p>\n<p>Trust <strong>Arivo Holidays</strong> to give you a wonderful itinerary where you can explore the Brahma Temple and enjoy an exciting Camel Safari near the Pushkar Lake. This trip is uniquely designed specially for you.</p>\n<p><strong>Scroll down to find our hand-picked tour packages and book your dream vacation! 👇</strong></p>" },
  { slug: 'fatehpur-sikri', html: "<p><strong>Are you hoping to visit the Buland Darwaza and experience exploring stunning Mughal Architecture in Fatehpur Sikri?</strong></p>\n<p><strong>Arivo Holidays</strong> brings you the ultimate itinerary allowing you to explore the Buland Darwaza and truly enjoy exploring stunning Mughal Architecture. This experience is uniquely planned for you.</p>\n<p><strong>Browse through our hand-picked tour list below and secure your booking! 👇</strong></p>" },
  { slug: 'vrindavan', html: "<p><strong>Are you looking to visit the Banke Bihari Temple and experience the spiritual atmosphere in Vrindavan?</strong></p>\n<p><strong>Arivo Holidays</strong> has structured a divine itinerary for you where you can peacefully explore the Banke Bihari Temple and enjoy the spiritual atmosphere. This is specially and uniquely planned for your comfort.</p>\n<p><strong>Scroll down to check our carefully selected tour packages and book your trip! 👇</strong></p>" },
  { slug: 'jodhpur', html: "<p><strong>Are you planning a trip to visit Mehrangarh Fort and experience exploring the vibrant Blue City streets in Jodhpur?</strong></p>\n<p>Look no further, as <strong>Arivo Holidays</strong> has designed the perfect itinerary for you to explore Mehrangarh Fort and enjoy exploring the vibrant Blue City streets. This holiday is planned uniquely and specially for you.</p>\n<p><strong>Find our exclusive tour packages below and click to begin your adventure! 👇</strong></p>" },
  { slug: 'alwar', html: "<p><strong>Are you thrilled to visit Bhangarh Fort and experience a thrilling Sariska Tiger Safari in Alwar?</strong></p>\n<p><strong>Arivo Holidays</strong> has expertly created an itinerary for you where you can explore Bhangarh Fort and enjoy a thrilling Sariska Tiger Safari. This is a very special and uniquely planned journey for you.</p>\n<p><strong>Scroll below to see our top-rated tour packages and book your dream trip! 👇</strong></p>" },
  { slug: 'mount-abu', html: "<p><strong>Are you seeking to visit the Dilwara Temples and experience a peaceful boat ride on Nakki Lake in Mount Abu?</strong></p>\n<p>With <strong>Arivo Holidays</strong>, you will receive the finest itinerary to explore the Dilwara Temples and comfortably enjoy a peaceful boat ride on Nakki Lake. This plan has been created uniquely for you.</p>\n<p><strong>Take a look at our hand-picked tour list below and book your ideal getaway! 👇</strong></p>" },
  { slug: 'ajmer', html: "<p><strong>Are you looking to visit the Ajmer Sharif Dargah and experience a relaxing walk near Ana Sagar Lake in Ajmer?</strong></p>\n<p><strong>Arivo Holidays</strong> has developed a wonderful itinerary for you where you can explore the Ajmer Sharif Dargah and enjoy a relaxing walk near Ana Sagar Lake. This trip is uniquely structured just for you.</p>\n<p><strong>Scroll down to check out our hand-picked tour packages below and click to book! 👇</strong></p>" },
  { slug: 'kota', html: "<p><strong>Are you eager to visit the Seven Wonders Park and experience exploring the Garh Palace by the Chambal River in Kota?</strong></p>\n<p>Trust <strong>Arivo Holidays</strong> for the best itinerary that lets you explore the Seven Wonders Park and enjoy exploring the Garh Palace by the Chambal River. This is specially and uniquely organized for you.</p>\n<p><strong>Explore our premium tour packages below and click to book your dream trip! 👇</strong></p>" },
  { slug: 'chittorgarh', html: "<p><strong>Are you wanting to visit the massive Chittorgarh Fort and experience learning about brave Rajput History in Chittorgarh?</strong></p>\n<p><strong>Arivo Holidays</strong> has created a historic itinerary for you where you can explore the massive Chittorgarh Fort and deeply enjoy learning about brave Rajput History. This unique plan is crafted specially for you.</p>\n<p><strong>Scroll down to check our hand-picked tour packages and secure your bookings! 👇</strong></p>" },
  { slug: 'shekhawati', html: "<p><strong>Are you looking to visit the Painted Havelis and experience discovering Traditional Frescoes in Shekhawati?</strong></p>\n<p><strong>Arivo Holidays</strong> offers a fantastic itinerary designed for you to explore the Painted Havelis and enjoy discovering Traditional Frescoes. This is a highly unique trip planned specially for you.</p>\n<p><strong>Find our exclusive tour list below and click to book your perfect holiday! 👇</strong></p>" },
  { slug: 'bundi', html: "<p><strong>Are you hoping to visit Taragarh Fort and experience exploring ancient Stepwells in Bundi?</strong></p>\n<p>Look no further! <strong>Arivo Holidays</strong> has crafted an incredible itinerary for you where you can explore Taragarh Fort and enjoy exploring ancient Stepwells. This travel plan is uniquely organized for you.</p>\n<p><strong>Scroll down to check our carefully selected tour packages and book your trip! 👇</strong></p>" },
  { slug: 'jaisalmer', html: "<p><strong>Are you planning to visit the Sonar Quila and experience a magical Camel Safari in the Thar Desert in Jaisalmer?</strong></p>\n<p><strong>Arivo Holidays</strong> has created the most vibrant itinerary for you to explore the Sonar Quila and enjoy a magical Camel Safari in the Thar Desert. This is uniquely planned specially for you.</p>\n<p><strong>Check out our hand-picked tour packages below and click to book your dream trip! 👇</strong></p>" },
  { slug: 'prayagraj', html: "<p><strong>Are you looking to visit the Triveni Sangam and experience the holy Kumbh Mela atmosphere in Prayagraj?</strong></p>\n<p>With <strong>Arivo Holidays</strong>, you get an exceptional itinerary to seamlessly explore the Triveni Sangam and enjoy the holy Kumbh Mela atmosphere. This journey is specially and uniquely planned for you.</p>\n<p><strong>Scroll down to explore our hand-picked tour list and book your spiritual trip! 👇</strong></p>" },
  { slug: 'dudhwa-national-park', html: "<p><strong>Are you thrilled to visit the deep jungles and experience a Wildlife Safari to spot Rhinos in Dudhwa National Park?</strong></p>\n<p><strong>Arivo Holidays</strong> has formulated an adventurous itinerary for you where you can explore the deep jungles and enjoy a Wildlife Safari to spot Rhinos. This is planned uniquely and exclusively for you.</p>\n<p><strong>Browse our top-tier tour packages below and click to book your adventure! 👇</strong></p>" },
  { slug: 'ayodhya', html: "<p><strong>Are you wanting to visit the Ram Janmabhoomi and experience a peaceful evening by the Sarayu River in Ayodhya?</strong></p>\n<p>Trust <strong>Arivo Holidays</strong> to deliver a deeply spiritual itinerary where you can explore the Ram Janmabhoomi and enjoy a peaceful evening by the Sarayu River. This plan is uniquely crafted for you.</p>\n<p><strong>Scroll down to check out our hand-picked tour packages below and click to book! 👇</strong></p>" },
  { slug: 'jhansi', html: "<p><strong>Are you looking to visit the historic Jhansi Fort and experience learning about the brave Rani Lakshmi Bai in Jhansi?</strong></p>\n<p><strong>Arivo Holidays</strong> has created a robust itinerary for you where you can explore the historic Jhansi Fort and enjoy learning about the brave Rani Lakshmi Bai. This is uniquely designed specially for you.</p>\n<p><strong>Find the best tour packages waiting for you below and click to secure your booking! 👇</strong></p>" },
  { slug: 'kushinagar', html: "<p><strong>Are you searching for a trip to visit the Mahaparinirvana Temple and experience a peaceful Buddhist Pilgrimage in Kushinagar?</strong></p>\n<p><strong>Arivo Holidays</strong> provides a magnificent itinerary allowing you to explore the Mahaparinirvana Temple and deeply enjoy a peaceful Buddhist Pilgrimage. This is a unique and specially planned trip for you.</p>\n<p><strong>Scroll down to check our premium tour packages and book your dream trip today! 👇</strong></p>" },
  { slug: 'mathura', html: "<p><strong>Are you planning to visit the Krishna Janmabhoomi and experience the vibrant temple festivals in Mathura?</strong></p>\n<p>Let <strong>Arivo Holidays</strong> guide you with an amazing itinerary where you can explore the Krishna Janmabhoomi and truly enjoy the vibrant temple festivals. This holiday is planned uniquely for you.</p>\n<p><strong>Check out our exclusive tour list below and click to begin your journey! 👇</strong></p>" },
  { slug: 'chitrakoot', html: "<p><strong>Are you looking to visit the Sacred Forests and experience the holy atmosphere at Ramghat in Chitrakoot?</strong></p>\n<p><strong>Arivo Holidays</strong> has created the most serene itinerary for you where you can explore the Sacred Forests and comfortably enjoy the holy atmosphere at Ramghat. This plan is specially and uniquely organized for you.</p>\n<p><strong>Scroll below to see our hand-picked tour packages and book your perfect getaway! 👇</strong></p>" },
  { slug: 'lucknow', html: "<p><strong>Are you eager to visit the Bara Imambara and experience the rich Awadhi Culture in Lucknow?</strong></p>\n<p>Look no further! <strong>Arivo Holidays</strong> has curated an excellent itinerary for you to explore the Bara Imambara and enjoy the rich Awadhi Culture. This experience is uniquely planned for you.</p>\n<p><strong>Take a look at our carefully selected tour packages below and book your ideal trip! 👇</strong></p>" },
  { slug: 'jammu', html: "<p><strong>Are you hoping to visit the Raghunath Temple and experience exploring the historic Bahu Fort in Jammu?</strong></p>\n<p><strong>Arivo Holidays</strong> has developed a fantastic itinerary for you where you can explore the Raghunath Temple and enjoy exploring the historic Bahu Fort. We have uniquely planned this journey just for you.</p>\n<p><strong>Scroll down to check our premium tour packages and click to book your adventure! 👇</strong></p>" },
  { slug: 'patnitop', html: "<p><strong>Are you ready to visit the Snow Mountains and experience thrilling Paragliding flights in Patnitop?</strong></p>\n<p>With <strong>Arivo Holidays</strong>, you get an adrenaline-filled itinerary allowing you to explore the Snow Mountains and enjoy thrilling Paragliding flights. This plan has been created uniquely for you.</p>\n<p><strong>Find our exclusive tour packages below and click to book your dream trip! 👇</strong></p>" },
  { slug: 'sonamarg', html: "<p><strong>Are you dreaming of visiting the Thajiwas Glacier and experiencing trekking through the Meadow of Gold in Sonamarg?</strong></p>\n<p><strong>Arivo Holidays</strong> has structured a breathtaking itinerary for you where you can explore the Thajiwas Glacier and enjoy trekking through the Meadow of Gold. This is specially and uniquely planned for you.</p>\n<p><strong>Scroll down to explore our hand-picked tour list and book your holiday today! 👇</strong></p>" },
  { slug: 'gulmarg', html: "<p><strong>Are you looking forward to visiting the Snow Mountains and experiencing riding the famous Gondola Cable Car in Gulmarg?</strong></p>\n<p>Trust <strong>Arivo Holidays</strong> to give you a snowy itinerary where you can explore the Snow Mountains and enjoy riding the famous Gondola Cable Car. This is planned uniquely and exclusively for you.</p>\n<p><strong>Check out our hand-picked tour packages below and click to secure your bookings! 👇</strong></p>" },
  { slug: 'aharbal-waterfall', html: "<p><strong>Are you hoping to visit the Niagara Falls of Kashmir and experience enjoying the scenic beauty in Aharbal Waterfall?</strong></p>\n<p><strong>Arivo Holidays</strong> has crafted a mesmerizing itinerary for you where you can explore the Niagara Falls of Kashmir and purely enjoy the scenic beauty. This unique plan is crafted specially for you.</p>\n<p><strong>Scroll down to check our top-rated tour packages and book your ideal trip! 👇</strong></p>" },
  { slug: 'aru-valley', html: "<p><strong>Are you seeking a trip to visit the Lush Meadows and experience trekking beside Crystal Clear Rivers in Aru Valley?</strong></p>\n<p><strong>Arivo Holidays</strong> brings you the most relaxing itinerary so you can explore the Lush Meadows and comfortably enjoy trekking beside Crystal Clear Rivers. This is a uniquely and specially planned trip for you.</p>\n<p><strong>Take a look at our fantastic tour packages below and book your ideal trip! 👇</strong></p>" }
];

async function updatePageOverviews() {
  console.log(`Starting pageOverview update for ${overviews.length} cities...`);
  let successCount = 0;
  
  for (const city of overviews) {
    try {
      const result = await prisma.city.updateMany({
        where: { slug: city.slug },
        data: { overView: city.html }
      });
      if (result.count > 0) {
        console.log(`✅ Updated: ${city.slug}`);
        successCount++;
      } else {
        console.log(`⚠️ Not found/No update: ${city.slug}`);
      }
    } catch (e) {
      console.error(`❌ Error updating ${city.slug}:`, e.message);
    }
  }
  console.log(`\nUpdate completed! Successfully updated ${successCount} cities.`);
}

updatePageOverviews().finally(() => prisma.$disconnect());
