-- Add SEO fields to all content models
-- NOTE: content tables may be created via `prisma db push`, so guard with IF EXISTS / IF NOT EXISTS
-- to keep shadow-database replay and fresh deployments working.

ALTER TABLE IF EXISTS "Journey" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "Journey" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "Journey" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "country" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "country" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "country" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "State" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "State" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "State" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "City" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "City" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "City" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "Month" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "Month" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "Month" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "TravelExperience" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "TravelExperience" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "TravelExperience" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "CmsPage" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "CmsPage" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "CmsPage" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;

ALTER TABLE IF EXISTS "BlogPost" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE IF EXISTS "BlogPost" ADD COLUMN IF NOT EXISTS "seoMetaDescription" TEXT;
ALTER TABLE IF EXISTS "BlogPost" ADD COLUMN IF NOT EXISTS "seoKeyword" TEXT;
